#include "levels.h"
#include "plants.h"
#include "lawnmower.h"
#include <c64/vic.h>

const Level	*	level;
char			level_cmd, level_size, level_conveyor, level_index, level_phase, level_delay;
unsigned		level_brains;
LevelCommand	level_command;


char			level_rows[32];

struct ZombieInfo
{
	char			cost, num;
	char			phase, level;
};

static const char	delayinfo[11] = {
	1, 2, 3, 5, 10, 25, 50, 75, 100, 125, 150
};

static const ZombieInfo	zombieInfos[LVC_ZOMBIE_GRAVES] = {
	[LVC_ZOMBIE] 			= {1,  25, 0, 0},
	[LVC_ZOMBIE_CONE] 		= {3,  13, 3, 0},
	[LVC_ZOMBIE_POLE]		= {4,   8, 4, 1},
	[LVC_ZOMBIE_BUCKET]		= {6,   8, 5, 2},
	[LVC_ZOMBIE_PAPER]		= {5,   4, 5, 3},
	[LVC_ZOMBIE_SCREENDOOR]	= {7,   3, 5, 4},
	[LVC_ZOMBIE_FOOTBALL]	= {10,  2, 6, 5},
	[LVC_ZOMBIE_DANCER]		= {15,  1, 6, 6}
};

static LevelCommand	zshuffle[64];


static const LevelCommand	LevelDayCmds1[] = {
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_5S | LVC_ZOMBIE,
	LVC_DELAY_5S | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_5S | LVC_ZOMBIE,
	LVC_DELAY_30F |	LVC_ZOMBIE,
	LVC_END
};

static const LevelCommand	LevelDayCmds2[] = {
	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,
	
	LVC_DELAY_10S |	LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,

	LVC_DELAY_30S |	LVC_ZOMBIE,

	LVC_DELAY_5S | LVC_ZOMBIE,
	LVC_DELAY_20F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds3[] = {
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,

	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_2S | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds4[] = {
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_15S |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds6[] = {
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S |	LVC_ZOMBIE_POLE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds7[] = {
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F |  LVC_ZOMBIE_CONE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_30S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_1S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_30F | LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds8[] = {
	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_30S |	LVC_ZOMBIE,

	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_BUCKET,

	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_END
};


static const LevelCommand	LevelDayCmds9[] = {
	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_30S |	LVC_ZOMBIE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_POLE,

	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,
	
	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_30S |	LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds10[] = {
	LVC_DELAY_5S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_25S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_25S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,

	LVC_DELAY_15S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,

	LVC_DELAY_10S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_15S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,

	LVC_DELAY_10S |	LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_POLE,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE_BUCKET,

	LVC_DELAY_30S |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_20F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20F |	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20F |	LVC_ZOMBIE_BUCKET,

	LVC_END
};


static const Level	LevelDay1 = {
	P"DAY 1",
	0b00100,
	LF_DAY | LF_FIXSEED,
	0, 1,
	300,
	SF_PEASHOOTER,
	LevelDayCmds1,
	TUNE_GAME_1,
	PT_PEASHOOTER_0,
	P"PLANT PEASHOOTERS\nTO PROTECT\nAGAINST ZOMBIES"
};

static const Level	LevelDay2 = {
	P"DAY 2",
	0b01110,
	LF_DAY | LF_FIXSEED,
	0, 2,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER,
	LevelDayCmds2,
	TUNE_GAME_2,
	PT_SUNFLOWER_0,
	P"SUNFLOWERS\nCOLLECT MORE\nSUN LIGHT"
};

static const Level	LevelDay3 = {
	P"DAY 3",
	0b01110,
	LF_DAY | LF_FIXSEED,
	0, 3,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB,
	LevelDayCmds3,
	TUNE_GAME_2,
	PT_CHERRYBOMB,
	P"BLOW UP ALL\nZOMBIES IN AN AREA"
};

static const Level	LevelDay4 = {
	P"DAY 4",
	0b11111,
	LF_DAY | LF_FIXSEED,
	0, 4,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT,
	LevelDayCmds4,
	TUNE_GAME_1,
	PT_WALLNUT_0,
	P"WALLNUTS PROTECT\nOTHER PLANTS"
};

static const Level	LevelDay6 = {
	P"DAY 6",
	0b11111,
	LF_DAY | LF_SHOVEL | LF_FIXSEED,
	0, 5,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE,
	LevelDayCmds6,
	TUNE_GAME_3,
	PT_POTATOMINE_0,
	P"POTATO MINES\nEXPLODE ON\nCONTACT"
};

static const Level	LevelDay7 = {
	P"DAY 7",
	0b11111,
	LF_DAY | LF_SHOVEL | LF_FIXSEED,
	0, 6,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA,
	LevelDayCmds7,
	TUNE_GAME_2,
	PT_SNOWPEA_0,
	P"SNOW PEAS FREEZE\nAND SLOW THE ENEMY"
};

static const Level	LevelDay8 = {
	P"DAY 8",
	0b11111,
	LF_DAY | LF_SHOVEL,
	0, 6,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER,
	LevelDayCmds8,
	TUNE_GAME_1
};

static const Level	LevelDay9 = {
	P"DAY 9",
	0b11111,
	LF_DAY | LF_SHOVEL,
	0, 6,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER,
	LevelDayCmds9,
	TUNE_GAME_3
};

static const Level	LevelDay10 = {
	P"DAY 10",
	0b11111,
	LF_DAY | LF_CONVEYOR | LF_SHOVEL,
	0, 6,
	50,
	SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER,
	LevelDayCmds10,
	TUNE_CONVEYOR
};

static const LevelCommand	LevelNightCmds1[] = {
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE_PAPER,
	LVC_DELAY_20S | LVC_ZOMBIE_PAPER,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_PAPER,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE_PAPER,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelNightCmds2[] = {
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_15S | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_20S | LVC_ZOMBIE_BUCKET,

	LVC_DELAY_20S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F |	LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F |	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F |	LVC_ZOMBIE_PAPER,

	LVC_DELAY_10S | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F |	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_5S  | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_PAPER,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_END
};

static const LevelCommand	LevelNightCmds3[] = {
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE_CONE,
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_20S | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE_SCREENDOOR,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_5S  | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,

	LVC_END
};

static const LevelCommand	LevelNightCmds4[] = {
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_20S | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE_POLE,
	LVC_DELAY_15S | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_5S  | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_5S  | LVC_ZOMBIE_CONE,
	LVC_DELAY_10S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_2S  | LVC_ZOMBIE_POLE,

	LVC_DELAY_10S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_5S  | LVC_ZOMBIE_POLE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelNightCmds6[] = {
	LVC_DELAY_25S | LVC_ZOMBIE,
	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10S | LVC_ZOMBIE_FOOTBALL,

	LVC_DELAY_25S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_5S | LVC_ZOMBIE_CONE,

	LVC_DELAY_25S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_FOOTBALL,
	
	LVC_DELAY_5S | LVC_ZOMBIE,	
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_END
};

static const LevelCommand	LevelNightCmds7[] = {
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_25S | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_25S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_FOOTBALL,

	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelNightCmds8[] = {
	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_15S | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE_DANCER,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_2S | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_25S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10S | LVC_ZOMBIE_DANCER,

	LVC_DELAY_2S | LVC_ZOMBIE,
	LVC_DELAY_2S | LVC_ZOMBIE_CONE,
	LVC_DELAY_2S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelNightCmds9[] = {
	LVC_DELAY_25S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_15S | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_30S | LVC_ZOMBIE,

	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_DANCER,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_DANCER,
	LVC_DELAY_2S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_15S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_1S | LVC_ZOMBIE_DANCER,

	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_END
};


static const LevelCommand	LevelNightCmds10[] = {

	LVC_DELAY_5S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_25S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_25S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_30S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE_DANCER,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_30S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,

	LVC_DELAY_30S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,

	LVC_DELAY_30S | LVC_ZOMBIE,
	LVC_DELAY_2S | LVC_ZOMBIE_FOOTBALL,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE_DANCER,
	LVC_DELAY_2S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_10S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_20S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_20S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_FOOTBALL,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,

	LVC_DELAY_10S | LVC_ZOMBIE_DANCER,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_FOOTBALL,
	LVC_DELAY_2S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_2S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_15S | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_2S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_FOOTBALL,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_DELAY_30S | LVC_ZOMBIE_GRAVES,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_DANCER,

	LVC_DELAY_2S | LVC_ZOMBIE_FOOTBALL,
	LVC_DELAY_2S | LVC_ZOMBIE_FOOTBALL,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_1S | LVC_ZOMBIE_SCREENDOOR,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE,
	LVC_DELAY_10F | LVC_ZOMBIE_CONE,

	LVC_END
};


static const Level	LevelNight1 = {
	P"NIGHT 1",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	4, 6,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM,
	LevelNightCmds1,
	TUNE_GAME_4
};

static const Level	LevelNight2 = {
	P"NIGHT 2",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	4, 6,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM,
	LevelNightCmds2,
	TUNE_GAME_5
};

static const Level	LevelNight3 = {
	P"NIGHT 3",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	4, 6,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM| SF_FUMESHROOM,
	LevelNightCmds3,
	TUNE_GAME_6
};

static const Level	LevelNight4 = {
	P"NIGHT 4",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	8, 6,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM| SF_FUMESHROOM | SF_GRAVEDIGGER,
	LevelNightCmds4,
	TUNE_GAME_4
};

static const Level	LevelNight6 = {
	P"NIGHT 6",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	7, 7,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM| SF_FUMESHROOM | SF_GRAVEDIGGER,
	LevelNightCmds6,
	TUNE_GAME_5
};

static const Level	LevelNight7 = {
	P"NIGHT 7",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	11, 7,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM| SF_FUMESHROOM | SF_GRAVEDIGGER | SF_SCAREDYSHROOM,
	LevelNightCmds7,
	TUNE_GAME_6
};

static const Level	LevelNight8 = {
	P"NIGHT 8",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	7, 7,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM| SF_FUMESHROOM | SF_GRAVEDIGGER | SF_SCAREDYSHROOM | SF_ICESHROOM,
	LevelNightCmds8,
	TUNE_GAME_4
};

static const Level	LevelNight9 = {
	P"NIGHT 9",
	0b11111,
	LF_NIGHT | LF_SHOVEL,
	11, 7,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM| SF_FUMESHROOM | SF_GRAVEDIGGER | SF_SCAREDYSHROOM | SF_ICESHROOM | SF_DOOMSHROOM,
	LevelNightCmds9,
	TUNE_GAME_5
};

static const Level	LevelNight10 = {
	P"NIGHT 10",
	0b11111,
	LF_NIGHT | LF_SHOVEL | LF_CONVEYOR,
	13, 7,
	50,
	SF_PUFFSHROOM | SF_FUMESHROOM | SF_GRAVEDIGGER | SF_SCAREDYSHROOM | SF_ICESHROOM | SF_DOOMSHROOM,
	LevelNightCmds10,
	TUNE_CONVEYOR
};

const Level	*	GameLevels[] = {
	&LevelDay1,
	&LevelDay2,
	&LevelDay3,
	&LevelDay4,
//	&LevelDay5,
	&LevelDay6,
	&LevelDay7,
	&LevelDay8,
	&LevelDay9,
	&LevelDay10,

	&LevelNight1,
	&LevelNight2,
	&LevelNight3,
	&LevelNight4,
	&LevelNight6,
	&LevelNight7,
	&LevelNight8,
	&LevelNight9,
	&LevelNight10,
};

char NighmareText[13] = P"NIGHTMARE 00";

Level	LevelNightmare = {
	NighmareText,
	0b11111,
	LF_NIGHT | LF_SHOVEL | LF_GENERATED,
	13, 8,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_PUFFSHROOM | SF_SUNSHROOM| SF_FUMESHROOM | SF_GRAVEDIGGER | SF_SCAREDYSHROOM | SF_ICESHROOM | SF_DOOMSHROOM,
	nullptr,
	TUNE_GAME_5	
};

static unsigned level_seed;

unsigned int level_rand(void)
{
    level_seed ^= level_seed << 7;
    level_seed ^= level_seed >> 9;
    level_seed ^= level_seed << 8;
	return level_seed;
}

static LevelCommand randzombie(void)
{
	char	k = level_rand() & 31;
	LevelCommand	z = zshuffle[k];
	while (k < 63)
	{
		zshuffle[k] = zshuffle[k + 1];
		k++;
	}
	zshuffle[63] = z;
	return z;
}

static const Tune	level_tunes[8] = {
	TUNE_GAME_1,
	TUNE_GAME_2,
	TUNE_GAME_3,
	TUNE_GAME_4,

	TUNE_GAME_5,
	TUNE_GAME_6,
	TUNE_GAME_2,
	TUNE_GAME_5,
};



void level_start(char li)
{
	level_cmd = 0;
	level_delay = 0;
	level_conveyor = 0;
	level_command = 0;
	level_size = 0;
	level_phase = 0;
	level_brains = 0;

	if (li >= 18)
	{
		level_index = li - 18;

		level = &LevelNightmare;
		NighmareText[10] = (level_index + 1) / 10 + '0';
		NighmareText[11] = (level_index + 1) % 10 + '0';

		level_size = level_index + 6;

		level_seed = level_index * 57 + level_index * 371 + level_index * 1131+ 0x3271;

		LevelNightmare.graves = 7 + level_index;
		LevelNightmare.tune = level_tunes[level_index & 7];

		char	t = 0;
		for(char i=0; i<8; i++)
		{
			for(char j=0; j<zombieInfos[i].num; j++)
				zshuffle[t++] = i;
		}		

		for(char i=0; i<64; i++)
			randzombie();
	}
	else
	{
		level = GameLevels[li];

		while (level->cmds[level_size] != LVC_END)
			level_size++;
	}


	char row = 0;
	for(char i=0; i<32; i++)
	{		
		do
		{
			row++;
			if (row == 5)
				row = 0;
		}
		while (!(level->rows & (1 << row)));

		level_rows[i] = row;
	}

	if (level->flags & LF_NIGHT)
	{
		back_color = VCOL_PURPLE << 4;
		back_tile = PT_NONE_NIGHT;
	}
	else
	{
		back_color = VCOL_GREEN << 4;
		back_tile = PT_NONE_DAY;
	}

	plant_draw_borders();

	if (level->flags & LF_CONVEYOR)
		menu_init(10);
	else
		menu_init(level->slots + 1);

	mower_init();

	plant_grid_clear(level->rows);

	for(char i=0; i<level->graves; i++)
	{
		char x, y;
		do {
			y = rand() % 5;
			x = 4 + rand() % 5;
		} while (plant_grid[y][x].type > PT_GROUND);

		plant_place(x, y, PT_TOMBSTONE);
	}

	plant_grid_draw();

	menu_progress(0, level_size);

	unsigned	seeds = level->seeds;
	if (level->flags & LF_CONVEYOR)
	{
		for(char i=0; i<9; i++)
			menu_add_item(PT_CONVEYOR, 0, 0, false, false);

		if (level->flags & LF_SHOVEL)
			menu_add_item(PT_SHOVEL, 0, 0, true, false);
	}
	else
	{
		menu_add_item(PT_SUN, level->sun, 0, true, false);
		if (level->flags & LF_FIXSEED)
		{
			for(char i=0; i<15; i++)
			{
				if (seeds & (1u << i))
					menu_add_item(seed_info[i].plant, seed_info[i].cost, seed_info[i].warm, seed_info[i].ready, false);
			}
		}
		else
		{
			seeds_edit_menu(seeds, level->slots);
			plant_grid_draw();
		}

		if (level->flags & LF_SHOVEL)
			menu_add_item(PT_SHOVEL, 0, 0, true, false);
	}


	music_init(level->tune);

	music_active = true;
}

static const LevelCommand zombie_delays[8] = {
	LVC_DELAY_10F, LVC_DELAY_10F,
	LVC_DELAY_20F, LVC_DELAY_20F,
	LVC_DELAY_30F, LVC_DELAY_30F,
	LVC_DELAY_1S,
	LVC_DELAY_2S
};

LevelCommand level_next_command(void)
{
	if (level->flags & LF_GENERATED)
	{
		if (level_cmd == level_size)
			return LVC_END;

		char	di;
		if (level_brains == 0)
		{
			do 	{
				di = (level_rand() & 3) + 6;
				level_brains = ((long)((1 + level_cmd) * (4 + level_index)) * delayinfo[di]) >> 8;
			} while (level_brains < 1);

			di <<= 4;

			if (level_cmd + 1 == level_size)
				return LVC_ZOMBIE_GRAVES | di;
		}
		else
			di = zombie_delays[level_rand() & 7];

		LevelCommand	z;
		do 	{
			z = randzombie();
		} while (zombieInfos[z].cost > level_brains || zombieInfos[z].level > level_index || zombieInfos[z].phase > level_cmd);

		level_brains -= zombieInfos[z].cost;

		if (level_brains == 0)
			level_cmd++;

		return z | di;
	}
	else
	{
		return level->cmds[level_cmd++];
	}
}

void level_iterate(void)
{
	if (level->flags & LF_CONVEYOR)
	{
		if (level_conveyor > 0)
			level_conveyor--;
		else
		{
			char x = 0;
			while (x < menu_size && menu[x].type != PT_CONVEYOR)
				x++;
			if (x < menu_size)
			{
				unsigned	s = 0;
				do {
					s = rand() & 15;
				} while (!(level->seeds & (1 << s)));

				menu_add_item_at(x, seed_info[s].plant, 0, 32, false, true);
			}

			level_conveyor = 20;
		}
	}

	if (!level_delay)
	{
		level_command = level_next_command();

		switch(level_command & 0xf0)
		{
			case LVC_DELAY_10F:
				level_delay = 1;
				break;
			case LVC_DELAY_20F:
				level_delay = 2;
				break;
			case LVC_DELAY_30F:
				level_delay = 3;
				break;
			case LVC_DELAY_1S:
				level_delay = 5;
				break;
			case LVC_DELAY_2S:
				level_delay = 4;
				break;
			case LVC_DELAY_5S:
				level_delay = 25;
				break;
			case LVC_DELAY_10S:
				level_delay = 50;
				break;
			case LVC_DELAY_15S:
				level_delay = 75;
				break;
			case LVC_DELAY_20S:
				level_delay = 100;
				break;
			case LVC_DELAY_25S:
				level_delay = 125;
				break;
			case LVC_DELAY_30S:
				level_delay = 150;
				break;
		}
	}
	else
	{
		level_delay--;
		if (!level_delay)
		{
			char 	i = rand() & 15;
			char	row = level_rows[i];
			while (i < 31)
			{
				level_rows[i] = level_rows[i + 1];
				i++;
			}
			level_rows[31] = row;

			bool	done = true;

			switch (level_command & 0x0f)
			{
				case LVC_ZOMBIE:
					done = zombies_add(172, row, ZOMBIE_BASE, 0);
					break;

				case LVC_ZOMBIE_CONE:
					done = zombies_add(172, row, ZOMBIE_CONE, 0);
					break;			

				case LVC_ZOMBIE_POLE:
					done = zombies_add(172, row, ZOMBIE_POLE, 0);
					break;			

				case LVC_ZOMBIE_BUCKET:
					done = zombies_add(172, row, ZOMBIE_BUCKET, 0);
					break;			

				case LVC_ZOMBIE_PAPER:
					done = zombies_add(172, row, ZOMBIE_PAPER, 0);
					break;			

				case LVC_ZOMBIE_SCREENDOOR:
					done = zombies_add(172, row, ZOMBIE_SCREENDOOR, 0);
					break;			

				case LVC_ZOMBIE_FOOTBALL:
					done = zombies_add(172, row, ZOMBIE_FOOTBALL, 0);
					break;						

				case LVC_ZOMBIE_DANCER:
					done = zombies_add(172, row, ZOMBIE_DANCER, 0);
					break;						

				case LVC_ZOMBIE_GRAVES:
					zombies_grave(ZOMBIE_RESURRECT);
					break;

				case LVC_END:
					done = false;
					break;			
			}

			if (done)
				menu_progress(level_cmd, level_size);
			else
				level_delay = 5;
		}
	}
}

bool level_complete(void)
{
	return level_command == LVC_END;
}

