#include "levels.h"
#include "plants.h"

const Level	*	level;
char			level_cmd, level_size, level_conveyor;
unsigned		level_delay;

char			level_rows[32];


static const LevelCommand	LevelDayCmds1[] = {
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_5S,
	LVC_ZOMBIE,
	LVC_DELAY_5S,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,
	LVC_DELAY_5S,
	LVC_ZOMBIE,
	LVC_DELAY_20F,
	LVC_ZOMBIE,
	LVC_END
};

static const LevelCommand	LevelDayCmds2[] = {
	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	
	LVC_DELAY_10S,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_DELAY_5S,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,

	LVC_DELAY_30S,
	LVC_ZOMBIE,

	LVC_DELAY_5S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds3[] = {
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_2S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds4[] = {
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_15S,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds6[] = {
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_POLE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds7[] = {
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_20S,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_20S,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_ZOMBIE,

	LVC_DELAY_30S,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE,

	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_1S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,	
	LVC_ZOMBIE,
	LVC_DELAY_10F,	
	LVC_ZOMBIE,
	LVC_DELAY_10F,	
	LVC_ZOMBIE,
	LVC_DELAY_10F,	
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_DELAY_10F,	
	LVC_ZOMBIE,
	LVC_DELAY_10F,	

	LVC_END
};

static const LevelCommand	LevelDayCmds8[] = {
	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_30S,
	LVC_ZOMBIE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_BUCKET,

	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_END
};


static const LevelCommand	LevelDayCmds9[] = {
	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_30S,
	LVC_ZOMBIE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_POLE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,
	
	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,


	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_DELAY_1S,

	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_1S,

	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,
	LVC_DELAY_1S,

	LVC_ZOMBIE,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,
	LVC_DELAY_1S,

	LVC_ZOMBIE,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE,

	LVC_END
};

static const LevelCommand	LevelDayCmds10[] = {
	LVC_DELAY_5S,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_25S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_25S,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_20S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_POLE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_15S,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,

	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_ZOMBIE_POLE,

	LVC_DELAY_10S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_15S,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_CONE,

	LVC_DELAY_10S,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE,
	LVC_ZOMBIE_POLE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,

	LVC_DELAY_10S,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE_POLE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE_BUCKET,

	LVC_DELAY_30S,
	LVC_ZOMBIE,
	LVC_ZOMBIE_CONE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_CONE,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE,
	LVC_ZOMBIE,
	LVC_ZOMBIE_BUCKET,
	LVC_DELAY_10F,
	LVC_ZOMBIE_POLE,
	LVC_ZOMBIE,
	LVC_ZOMBIE_BUCKET,
	LVC_ZOMBIE,
	LVC_DELAY_10F,
	LVC_ZOMBIE_BUCKET,
	LVC_END
};

static const Level	LevelDay1 = {
	0b00100,
	LF_DAY,
	300,
	SF_PEASHOOTER,
	LevelDayCmds1,
	TUNE_GAME_1
};

static const Level	LevelDay2 = {
	0b01110,
	LF_DAY,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER,
	LevelDayCmds2,
	TUNE_GAME_2
};

static const Level	LevelDay3 = {
	0b01110,
	LF_DAY,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB,
	LevelDayCmds3,
	TUNE_GAME_2
};

static const Level	LevelDay4 = {
	0b11111,
	LF_DAY,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT,
	LevelDayCmds4,
	TUNE_GAME_1
};

static const Level	LevelDay6 = {
	0b11111,
	LF_DAY,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SHOVEL,
	LevelDayCmds6,
	TUNE_GAME_3
};

static const Level	LevelDay7 = {
	0b11111,
	LF_DAY,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_SHOVEL,
	LevelDayCmds7,
	TUNE_GAME_2
};

static const Level	LevelDay8 = {
	0b11111,
	LF_DAY,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_SHOVEL,
	LevelDayCmds8,
	TUNE_GAME_1
};

static const Level	LevelDay9 = {
	0b11111,
	LF_DAY,
	50,
	SF_SUNFLOWER | SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_SHOVEL,
	LevelDayCmds9,
	TUNE_GAME_3
};

static const Level	LevelDay10 = {
	0b11111,
	LF_DAY | LF_CONVEYOR,
	50,
	SF_PEASHOOTER | SF_CHERRYBOMB | SF_WALLNUT | SF_POTATOMINE | SF_SNOWPEA | SF_CHOMPER | SF_REPEATER | SF_SHOVEL,
	LevelDayCmds10,
	TUNE_GAME_2
};

const Level	*	GameLevels[] = {
	&LevelDay1,
	&LevelDay2,
	&LevelDay3,
	&LevelDay4,
//	&LevelDay5,
	&LevelDay6,
	&LevelDay7,
	&LevelDay8,
	&LevelDay9,
	&LevelDay10,
};

void level_start(const Level * l)
{
	level = l;
	level_cmd = 0;
	level_delay = 0;
	level_conveyor = 0;

	level_size = 0;
	while (level->cmds[level_size] != LVC_END)
		level_size++;

	char row = 0;
	for(char i=0; i<32; i++)
	{		
		do
		{
			row++;
			if (row == 5)
				row = 0;
		}
		while (!(l->rows & (1 << row)));

		level_rows[i] = row;
	}

	menu_init();

	unsigned	seeds = l->seeds;
	if (l->flags & LF_CONVEYOR)
	{
		for(char i=0; i<9; i++)
			menu_add_item(PT_CONVEYOR, 0, 0, false, false);
	}
	else
	{
		menu_add_item(PT_SUN, l->sun, 0, true, false);
		if (seeds & SF_SUNFLOWER)
			menu_add_item(PT_SUNFLOWER_0, 50, 17, true, false);
		if (seeds & SF_PEASHOOTER)
			menu_add_item(PT_PEASHOOTER_0, 100, 17, true, false);
		if (seeds & SF_SNOWPEA)
			menu_add_item(PT_SNOWPEA_0, 175, 17, false, false);
		if (seeds & SF_WALLNUT)
			menu_add_item(PT_WALLNUT_0, 50, 6, false, false);
		if (seeds & SF_POTATOMINE)
			menu_add_item(PT_POTATOMINE_0, 25, 6, false, false);
		if (seeds & SF_REPEATER)
			menu_add_item(PT_REPEATER_0, 200, 17, false, false);
		if (seeds & SF_CHERRYBOMB)
			menu_add_item(PT_CHERRYBOMB, 150, 3, false, false);
		if (seeds & SF_CHOMPER)
			menu_add_item(PT_CHOMPER_0, 150, 17, false, false);
	}

	if (seeds & SF_SHOVEL)
		menu_add_item(PT_SHOVEL, 0, 17, false, false);

	plant_grid_clear(l->rows);

	menu_progress(0, level_size);

	music_init(l->tune);
}

void level_iterate(void)
{
	if (level->flags & LF_CONVEYOR)
	{
		if (level_conveyor > 0)
			level_conveyor--;
		else
		{
			char x = 0;
			while (x < menu_size && menu[x].type != PT_CONVEYOR)
				x++;
			if (x < menu_size)
			{
				unsigned	s = 0;
				do {
					s = 1 << (rand() & 15);
				} while ((s == SF_SHOVEL) || !(level->seeds & s));

				if (s & SF_SUNFLOWER)
					menu_add_item_at(x, PT_SUNFLOWER_0, 0, 32, false, true);
				else if (s & SF_PEASHOOTER)
					menu_add_item_at(x, PT_PEASHOOTER_0, 0, 32, false, true);
				else if (s & SF_SNOWPEA)
					menu_add_item_at(x, PT_SNOWPEA_0, 0, 32, false, true);
				else if (s & SF_WALLNUT)
					menu_add_item_at(x, PT_WALLNUT_0, 0, 32, false, true);
				else if (s & SF_POTATOMINE)
					menu_add_item_at(x, PT_POTATOMINE_0, 0, 32, false, true);
				else if (s & SF_REPEATER)
					menu_add_item_at(x, PT_REPEATER_0, 0, 32, false, true);
				else if (s & SF_CHERRYBOMB)
					menu_add_item_at(x, PT_CHERRYBOMB, 0, 32, false, true);
				else if (s & SF_CHOMPER)
					menu_add_item_at(x, PT_CHOMPER_0, 0, 32, false, true);
			}

			level_conveyor = 20;
		}
	}

	if (level_delay)
		level_delay--;
	else
	{
		char 	i = rand() & 15;
		char	row = level_rows[i];
		while (i < 31)
		{
			level_rows[i] = level_rows[i + 1];
			i++;
		}
		level_rows[31] = row;

		switch (level->cmds[level_cmd])
		{
			case LVC_NOP:
				level_cmd++;
				break;

			case LVC_DELAY_10F:
				level_delay = 1;
				level_cmd++;
				break;
			case LVC_DELAY_20F:
				level_delay = 2;
				level_cmd++;
				break;
			case LVC_DELAY_1S:
				level_delay = 5;
				level_cmd++;
				break;
			case LVC_DELAY_2S:
				level_delay = 4;
				level_cmd++;
				break;
			case LVC_DELAY_5S:
				level_delay = 25;
				level_cmd++;
				break;
			case LVC_DELAY_10S:
				level_delay = 50;
				level_cmd++;
				break;
			case LVC_DELAY_15S:
				level_delay = 75;
				level_cmd++;
				break;
			case LVC_DELAY_20S:
				level_delay = 100;
				level_cmd++;
				break;
			case LVC_DELAY_25S:
				level_delay = 125;
				level_cmd++;
				break;
			case LVC_DELAY_30S:
				level_delay = 150;
				level_cmd++;
				break;
			case LVC_DELAY_60S:
				level_delay = 300;
				level_cmd++;
				break;

			case LVC_ZOMBIE:
				zombies_add(172, row, ZOMBIE_BASE);
				level_cmd++;				
				break;

			case LVC_ZOMBIE_CONE:
				zombies_add(172, row, ZOMBIE_CONE);
				level_cmd++;				
				break;			

			case LVC_ZOMBIE_POLE:
				zombies_add(172, row, ZOMBIE_POLE);
				level_cmd++;				
				break;			

			case LVC_ZOMBIE_BUCKET:
				zombies_add(172, row, ZOMBIE_BUCKET);
				level_cmd++;				
				break;			
		}

		menu_progress(level_cmd, level_size);
	}
}

bool level_complete(void)
{
	return level->cmds[level_cmd] == LVC_END;
}

